**<h1 align = "center"> Pandas Bascis-II </h1>**

#### Dataset: Ecommerce Sales Dataset

In [2]:
# import library
import pandas as pd

In [20]:
# load the dataset
df = pd.read_csv("ecommerce_sales_data.csv")

In [21]:
# display the first 5 rows of the dataset
df.head()

,Year,Month,Category,Region,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend
0,2020,April,Home Decor,North,485,94360.58,25442.39,1.5,174.51
1,2021,October,Fashion,South,95,14081.40,3457.23,3.5,3975.18
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31
3,2020,April,Fashion,South,419,81856.23,20726.68,2.8,3706.92
4,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07

In [22]:
# shape of the dataset (rows, codf.shape
df.shape

(1000, 9)

In [23]:
# display column names
df.columns

Index(['Year', 'Month', 'Category', 'Region', 'Units_Sold', 'Revenue',
       'Profit', 'Customer_Rating', 'Ad_Spend'],
      dtype='str')

In [24]:
# unique values in the "Product Category" column
df["Category"].unique()

<StringArray>
['Home Decor', 'Fashion', 'Groceries', 'Beauty Products', 'Books',
 'Electronics']
Length: 6, dtype: str

In [25]:
# product category sales count
df["Category"].value_counts()

Category
Electronics        178
Home Decor         172
Beauty Products    168
Fashion            167
Groceries          159
Books              156
Name: count, dtype: int64

In [29]:
# Filter required columns
df_filtered = df[["Year", "Category", "Units_Sold", "Revenue"]]
df_filtered.head()

   Year         Category  Units_Sold   Revenue
0  2020       Home Decor         485  94360.58
1  2021          Fashion          95  14081.40
2  2022        Groceries         182  13700.50
3  2020          Fashion         419  81856.23
4  2020  Beauty Products         469  51810.41

In [30]:
# filter the dataset for the year > 2021
df[df["Year"] > 2021]

,Year,Month,Category,Region,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31
8,2022,December,Books,East,93,2786.24,756.29,1.9,1089.83
9,2023,February,Books,West,43,7338.19,1452.80,2.2,2668.78
11,2023,July,Fashion,South,409,4092.73,1218.10,4.6,1329.19
12,2022,January,Electronics,East,256,5863.97,1574.05,2.2,3327.72
...,...,...,...,...,...,...,...,...,...
988,2023,May,Home Decor,South,321,17584.98,4336.50,1.1,1436.07
992,2023,May,Electronics,West,220,36700.75,10785.11,1.5,1781.23
995,2023,January,Fashion,West,38,5606.14,1577.25,3.2,4788.84
996,2024,October,Groceries,East,422,13513.47,2667.70,3.1,495.29
998,2024,May,Groceries,South,434,66941.72,14621.33,2.5,2944.75

In [31]:
# filter dataset > 2021 and < 2024
df[(df["Year"] > 2021) & (df["Year"] < 2024)]

,Year,Month,Category,Region,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31
8,2022,December,Books,East,93,2786.24,756.29,1.9,1089.83
9,2023,February,Books,West,43,7338.19,1452.80,2.2,2668.78
11,2023,July,Fashion,South,409,4092.73,1218.10,4.6,1329.19
12,2022,January,Electronics,East,256,5863.97,1574.05,2.2,3327.72
...,...,...,...,...,...,...,...,...,...
985,2023,June,Groceries,North,459,83634.84,14872.89,1.2,3684.24
986,2022,December,Fashion,West,103,7125.27,2055.17,4.5,4496.49
988,2023,May,Home Decor,South,321,17584.98,4336.50,1.1,1436.07
992,2023,May,Electronics,West,220,36700.75,10785.11,1.5,1781.23
995,2023,January,Fashion,West,38,5606.14,1577.25,3.2,4788.84

In [32]:
# Filter category = "Books" and year = 2023
df[(df["Category"] == "Books") & (df["Year"] ==2023)]

,Year,Month,Category,Region,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend
9,2023,February,Books,West,43,7338.19,1452.80,2.2,2668.78
55,2023,March,Books,East,380,15520.90,2343.03,4.6,2837.74
62,2023,May,Books,South,165,8454.10,1063.72,1.7,3481.41
65,2023,October,Books,South,421,15004.20,1526.95,2.3,2067.17
78,2023,June,Books,North,122,11240.79,3250.72,3.2,1713.08
107,2023,February,Books,North,122,9396.10,1658.88,3.8,2787.23
127,2023,May,Books,East,102,5332.20,619.75,4.8,3014.68
141,2023,March,Books,South,262,44301.13,5227.03,3.8,1657.79
189,2023,September,Books,West,374,64907.32,17567.40,1.7,3654.43
207,2023,January,Books,South,315,7911.59,969.80,2.6,1146.51
212,2023,June,Books,East,56,8760.19,1202.31,3.1,3111.17
230,2023,April,Books,North,167,14895.52,3001.56,4.4,2892.83
287,2023,July,Books,North,287,28801.89,7396.51,2.6,3219.10
309,2023,July,Books,North,341,45700.54,6384.21,3.5,4032.97
328,2023,July,Books,North,230,42530.26,10078.69,3.9,4118.53
339,2023,August,Books,South,483,49188.93,11848.91,3.3,2783.34
407,2023,October,Books,North,491,22657.60,2374.92,3.7,1627.26
417,2023,January,Books,North,244,16036.70,4168.83,1.1,3871.99
453,2023,February,Books,West,428,32956.19,8836.15,3.4,4113.42
546,2023,July,Books,West,159,1886.87,455.36,2.0,1558.11
590,2023,December,Books,West,97,12406.51,2147.85,3.3,2075.10
710,2023,October,Books,West,33,4966.81,861.58,3.0,2696.09
743,2023,March,Books,East,437,44833.96,7343.07,3.1,3096.11
797,2023,February,Books,South,271,11505.55,1408.93,1.2,1379.97
806,2023,December,Books,North,36,6483.42,648.93,2.8,3816.29
819,2023,January,Books,South,380,12967.23,2356.32,3.7,4871.74
865,2023,December,Books,West,249,21741.57,5166.23,2.9,4059.59
895,2023,April,Books,South,73,14283.78,1987.86,2.6,1263.09
915,2023,August,Books,North,477,48249.70,8237.87,2.0,3848.40
959,2023,September,Books,North,242,36541.15,6162.95,4.3,1582.93
975,2023,January,Books,South,455,16452.67,2398.09,3.0,4081.20

In [33]:
# describe the dataset
df.describe()

,Year,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2021.955000,263.337000,27123.544520,5494.732660,3.040200,2649.554610
std,1.367057,137.701086,22261.011837,5041.842396,1.161599,1408.662125
min,2020.000000,20.000000,541.780000,83.910000,1.000000,101.940000
25%,2021.000000,138.000000,8451.205000,1612.855000,2.000000,1429.070000
50%,2022.000000,268.500000,20743.015000,3820.585000,3.100000,2724.605000
75%,2023.000000,381.250000,41275.547500,7989.782500,4.000000,3888.252500
max,2024.000000,500.000000,96923.930000,25675.500000,5.000000,4997.660000

In [34]:
# info about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             1000 non-null   int64
 1   Month            1000 non-null   str
 2   Category         1000 non-null   str
 3   Region           1000 non-null   str
 4   Units_Sold       1000 non-null   int64
 5   Revenue          1000 non-null   float64
 6   Profit           1000 non-null   float64
 7   Customer_Rating  1000 non-null   float64
 8   Ad_Spend         1000 non-null   float64
dtypes: float64(4), int64(2), str(3)
memory usage: 70.4 KB

In [36]:
# min and max ratings
print("Minimum Rating", df["Customer_Rating"].min())
print("Maximum Rating", df["Customer_Rating"].max())

Minimum Rating 1.0
Maximum Rating 5.0

In [54]:
# create a new column "Revenue_per_Unit" by dividing "Revenue" by "Units_Sold" upto 2 decimal places
df["Revenue_per_Unit"] = (df["Revenue"] / df["Units_Sold"]).round(2)

In [55]:
df.head()

,Year,Month,Category,Region,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend,Revenue_per_Unit
0,2020,April,Home Decor,North,485,94360.58,25442.39,1.5,174.51,194.56
1,2021,October,Fashion,South,95,14081.40,3457.23,3.5,3975.18,148.23
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31,75.28
3,2020,April,Fashion,South,419,81856.23,20726.68,2.8,3706.92,195.36
4,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07,110.47