**<h1 align = "center"> DataFrame Operations in Pandas </h1>**

- 1. Merge DataFiles
- 2. Save DataFile
- 3. Create DataFrame
- 4. Export DataFrame (openpyxl install)

In [1]:
# import pandas library
import pandas as pd

In [2]:
# import data file
df = pd.read_csv("ecommerce_sales_data.csv")
df.head()

,Year,Month,Category,Region,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend
0,2020,April,Home Decor,North,485,94360.58,25442.39,1.5,174.51
1,2021,October,Fashion,South,95,14081.40,3457.23,3.5,3975.18
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31
3,2020,April,Fashion,South,419,81856.23,20726.68,2.8,3706.92
4,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07

In [3]:
# filter specific cols for file-1
df_cat = df[["Year", "Category", "Region"]]
# save in csv file
df_cat.to_csv("ProductsFile.csv", index = False)
# load file
df_prod = pd.read_csv("ProductsFile.csv")
df_prod.head()

   Year         Category Region
0  2020       Home Decor  North
1  2021          Fashion  South
2  2022        Groceries   East
3  2020          Fashion  South
4  2020  Beauty Products  North

In [4]:
# filter specific cols for file-2
df_cat_sold = df[["Category", "Units_Sold", "Revenue", "Profit"]]
# save in csv file
df_cat_sold.to_csv("ProductsSold.csv", index = False)
# Load file
df_sold = pd.read_csv("ProductsSold.csv")
df_sold.head()

          Category  Units_Sold   Revenue    Profit
0       Home Decor         485  94360.58  25442.39
1          Fashion          95  14081.40   3457.23
2        Groceries         182  13700.50   3985.61
3          Fashion         419  81856.23  20726.68
4  Beauty Products         469  51810.41   5624.12

### 1. Merge Datafiles

In [5]:
# merge two datafiles based on one similar col.
df_merged_files = pd.merge(df_prod, df_sold, on = "Category")
df_merged_files.head()

   Year    Category Region  Units_Sold   Revenue    Profit
0  2020  Home Decor  North         485  94360.58  25442.39
1  2020  Home Decor  North         127  13621.99   1581.60
2  2020  Home Decor  North         190   6439.93   1767.44
3  2020  Home Decor  North         287  26345.19   6822.97
4  2020  Home Decor  North         384  38287.41   6894.60

### 2. Save File

In [6]:
# save merge file
df_merged_files.to_csv("Merged_File.csv", index = False)

### 3. Create DataFrames and Save in Excel Sheets
- This create with key value pair of dict.

In [7]:
# create dataframe
df_cost = pd.DataFrame({
    "Category": ["Home", "Books", "Fashion"],
    "Quantit" : [200, 345, 455],
    "Cost": [3000, 4000, 1000]
    
})
print(df_cost)

  Category  Quantit  Cost
0     Home      200  3000
1    Books      345  4000
2  Fashion      455  1000

In [8]:
# 2nd DataFrame
df_revenue = pd.DataFrame({
    "Category" : ["Medical", "Electronics", "Home"],
    "Sold" : [123, 456, 500],
    "Revenue" : [1000, 35000, 4000]
})
print(df_revenue)

      Category  Sold  Revenue
0      Medical   123     1000
1  Electronics   456    35000
2         Home   500     4000

In [14]:
# Save/Export in Excel Sheet
with pd.ExcelWriter("Cost_Revenue.xlsx") as writer:
    df_cost.to_excel(writer, sheet_name = "Cost", index = False)
    df_revenue.to_excel(writer, sheet_name = "Revenue", index = False)